// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using uploadApi.Context;

namespace uploadApi.Migrations
{
    [DbContext(typeof(ArquivoContext))]
    partial class ArquivoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("uploadApi.Models.Arquivos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SavedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("URLImagem")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Arquivos");
                });
#pragma warning restore 612, 618
        }
    }
}
