// <auto-generated />
using System;
using CadastroPessoa.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CadastroPessoa.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250207035851_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CadastroPessoa.Domain.Models.Contato", b =>
                {
                    b.Property<int>("IdContato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idContato");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdContato"));

                    b.Property<string>("NomeContato")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nomeContato");

                    b.Property<int?>("PessoaId")
                        .HasColumnType("integer")
                        .HasColumnName("pessoaId");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("IdContato");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.ToTable("contatos", (string)null);
                });

            modelBuilder.Entity("CadastroPessoa.Domain.Models.Pessoa", b =>
                {
                    b.Property<int>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idPessoa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPessoa"));

                    b.Property<int?>("ContatoId")
                        .HasColumnType("integer")
                        .HasColumnName("contatoId");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("NomePessoa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nomePessoa");

                    b.HasKey("IdPessoa");

                    b.ToTable("pessoas", (string)null);
                });

            modelBuilder.Entity("CadastroPessoa.Domain.Models.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idProduto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProduto"));

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nomeProduto");

                    b.Property<int?>("PessoaId")
                        .HasColumnType("integer")
                        .HasColumnName("pessoaId");

                    b.Property<string>("Preco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preco");

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipoProduto");

                    b.HasKey("IdProduto");

                    b.HasIndex("PessoaId");

                    b.ToTable("produtos", (string)null);
                });

            modelBuilder.Entity("CadastroPessoa.Domain.Models.Contato", b =>
                {
                    b.HasOne("CadastroPessoa.Domain.Models.Pessoa", "Pessoa")
                        .WithOne("Contato")
                        .HasForeignKey("CadastroPessoa.Domain.Models.Contato", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Contato_PessoaId");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("CadastroPessoa.Domain.Models.Produto", b =>
                {
                    b.HasOne("CadastroPessoa.Domain.Models.Pessoa", "Pessoa")
                        .WithMany("Produtos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Produto_PessoaId");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("CadastroPessoa.Domain.Models.Pessoa", b =>
                {
                    b.Navigation("Contato");

                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
